#!/bin/bash

if [ ! -e enigma_app.cxx ]
then
	echo "This script must be run in the repository root directory!"
	exit 1
fi

rm -rf build
rm -rf bin

if [ $# -eq 0 ];then
	export BOOSTINCLUDE=/usr/local/opt/boost/include
elif [ "$1" = --boost-libs ];then
	echo "Will search for Boost Library at: '$2'"
	export BOOSTINCLUDE=$2
else
	echo "Invalid argument"
fi

mkdir -p build
cd build
cmake ..
make
cd -
echo "Installation of M3 Test Successful, binary can be found at '${PWD}/bin/enigmaM3_test'"
