name: Enigma

on: [push]

jobs:
    build: 
        name: ${{ matrix.os }} ${{ matrix.config.compiler }}
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            os:  ['ubuntu-latest', 'macos-latest']
            config: [{
              compiler: gcc,
              compilerpp:  g++
            },
            {
              compiler: clang,
              compilerpp: clang++
            }]
        steps:
            - uses: actions/checkout@v2

            - name: Install Brew (macOS)
              run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
              if: matrix.os == 'macos-latest'

            - name: Install Boost (macOS)
              run: brew install boost
              if: matrix.os == 'macos-latest'
            
            - name: Install Boost and LCov (Ubuntu)
              run: sudo apt upgrade && sudo apt update && sudo apt install libboost-all-dev lcov -y
              if: matrix.os == 'ubuntu-latest'

            - name: Checkout Logging submodule
              run: git submodule update --init --recursive
            
            - name: Compile
              env:
                CC: ${{ matrix.config.compiler }}
                CXX: ${{ matrix.config.compilerpp }}
              run: |
                mkdir build
                cd build
                cmake ..
                make
            
            - name: Run Unit Tests
              run: |
                ./tests/bin/Enigma-unit_tests
                if [ $? -eq 0 ]; then
                    echo "Unit tests completed successfully"
                exit 0
                else
                    echo "Unit tests failed"
                    exit 1
                fi
                
            - name: Run Coverage (Ubuntu GCC)
              run: |
                make coverage
                bash <(curl -s https://codecov.io/bash) -f build/Enigma.info || echo "Codecov did not collect coverage reports"
              continue-on-error: true # Do not want failed coverage to mean failed build!
              if: matrix.os == 'ubuntu-latest' && matrix.config.compiler == 'clang'